spring:
  application:
    name: address-service
  profiles:
    active: dev
#mybatis:
#  mapper-locations: classpath*:base/platform/req/mapper/*Mapper.xml"
#  type-aliases-package: base.platform.req.model
server:
  port: 8802
